INSERT INTO LANGUAGES (LANGUAGE) VALUES ('English');
INSERT INTO LANGUAGES (LANGUAGE) VALUES ('Spanish');
INSERT INTO WORDS (WORD) VALUES ('Hello');
INSERT INTO WORDS (WORD) VALUES ('People');
INSERT INTO WORDS (WORD) VALUES ('Big');
INSERT INTO WORDS (WORD) VALUES ('and');
INSERT INTO TARGETS (TARGET, WORD_ID, LANGUAGE_ID) VALUES ('Gente', (SELECT WORD_ID FROM WORDS WHERE WORD = 'People'), (SELECT LANGUAGE_ID FROM LANGUAGES WHERE LANGUAGE = 'Spanish'));
INSERT INTO TARGETS (TARGET, WORD_ID, LANGUAGE_ID) VALUES ('Hola', (SELECT WORD_ID FROM WORDS WHERE WORD = 'Hello'), (SELECT LANGUAGE_ID FROM LANGUAGES WHERE LANGUAGE = 'Spanish'));
INSERT INTO TARGETS (TARGET, WORD_ID, LANGUAGE_ID) VALUES ('Grande', (SELECT WORD_ID FROM WORDS WHERE WORD = 'Big'), (SELECT LANGUAGE_ID FROM LANGUAGES WHERE LANGUAGE = 'Spanish'));
INSERT INTO TARGETS (TARGET, WORD_ID, LANGUAGE_ID) VALUES ('y', (SELECT WORD_ID FROM WORDS WHERE WORD = 'and'), (SELECT LANGUAGE_ID FROM LANGUAGES WHERE LANGUAGE = 'Spanish'));
INSERT INTO TARGETS (TARGET, WORD_ID, LANGUAGE_ID) VALUES ('People', (SELECT WORD_ID FROM WORDS WHERE WORD = 'People'), (SELECT LANGUAGE_ID FROM LANGUAGES WHERE LANGUAGE = 'English'));
INSERT INTO TARGETS (TARGET, WORD_ID, LANGUAGE_ID) VALUES ('Hello', (SELECT WORD_ID FROM WORDS WHERE WORD = 'Hello'), (SELECT LANGUAGE_ID FROM LANGUAGES WHERE LANGUAGE = 'English'));
INSERT INTO TARGETS (TARGET, WORD_ID, LANGUAGE_ID) VALUES ('Big', (SELECT WORD_ID FROM WORDS WHERE WORD = 'Big'), (SELECT LANGUAGE_ID FROM LANGUAGES WHERE LANGUAGE = 'English'));
INSERT INTO TARGETS (TARGET, WORD_ID, LANGUAGE_ID) VALUES ('and', (SELECT WORD_ID FROM WORDS WHERE WORD = 'and'), (SELECT LANGUAGE_ID FROM LANGUAGES WHERE LANGUAGE = 'English'));








