CREATE TABLE WORDS(
  WORD_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  WORD VARCHAR(64) NOT NULL,
);

CREATE TABLE LANGUAGES(
  LANGUAGE_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  LANGUAGE VARCHAR(64) NOT NULL,
);

CREATE TABLE TARGETS(
  TARGET_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  TARGET VARCHAR(64) NOT NULL,
  WORD_ID BIGINT NOT NULL,
  LANGUAGE_ID BIGINT NOT NULL,
);

ALTER TABLE TARGETS ADD FOREIGN KEY (WORD_ID) REFERENCES WORDS(WORD_ID);
ALTER TABLE TARGETS ADD FOREIGN KEY (LANGUAGE_ID) REFERENCES LANGUAGES(LANGUAGE_ID);

